
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopee"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
#  security:
#    user:
#      name: "admin"
#      password: "admin123"
  app:
    jwtSecret: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
    jwtExpirationMs: 300000000
    jwtCookieName: shoppe_clone_app

project:
  image: "images"

